name: notebooks-environment
channels:
  - conda-forge
dependencies:
  - python=3.9
  - descartes
  - esda
  - geopandas>=0.7.0
  - libspatialindex
  - matplotlib
  - numpy
  - pandas>=1.0
  - pulp
  - rtree
  - scipy>=1.0
  - seaborn
  - splot
  - watermark
  - pip
  - pip:
    - mip
    - ortools
    - matplotlib_scalebar
    - git+https://github.com/pysal/spaghetti.git@main
