name: notebooks-environment
channels:
  - conda-forge
dependencies:
  - python=3.10
  - esda
  - geopandas>=0.12.0
  - libspatialindex
  - matplotlib
  - matplotlib-scalebar
  - numpy
  - pandas>=1.0
  - pulp
  - rtree
  - scipy>=1.0
  - seaborn
  - shapely>=2
  - splot
  - watermark
  - pip
  - pip:
    - mip
    - ortools
    - git+https://github.com/pysal/spaghetti.git@main
