name: notebooks-environment
channels:
  - conda-forge
dependencies:
  - python=3.7
  - geopandas
  - descartes
  - rtree
  - libspatialindex
  - pulp
  - esda
  - matplotlib
  - matplotlib_scalebar
  - watermark
  - seaborn
  - pip
  - pip:
    - mip
    - ortools
    - git+https://github.com/pysal/spaghetti.git@master
